baseURL: https://jingyi-fang.netlify.app/
languageCode: en-us
title: "Jingyi Fang's website"
theme: "forty"
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    #subtitle: Nice to meet you :)!
    title: Hi, my name is Jingyi Fang!
  blog: {}
  contact:
    address:
      - city: London
        country: United Kingdom
        street: 1 Newcastle Place
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: jfang.mam2023@london.edu
        title: LBSEmail
    enable: yes
    phone:
      - phone: +44 7733210270
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Jingyi Fang
    enable: yes
    quicklinks:
    social:
      - icon: fa-instagram
        label: Instagram
        url: https://instagram.com/itsfbee
      - icon: fa-github
        label: GitHub
        url: https://github.com/jfang219
      - icon: fa-linkedin
        label: LinkedIn
        url: www.linkedin.com/in/fangjy
  image: ''
  name: Jingyi Fang
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: Generic Blog
        url: blogs/ipsum
      - name: Elements
        url: elements.html
    menu: 
  tiles:
    enable: yes
    showcase:
      - image: lbs.jpg
        subtitle: Example
        title: Risk Return
        url: blogs/risk_return
      - image: pic02.jpg
        subtitle: Jingyi Fang
        title: About Me
        url: blogs/about_me
      - image: pic03.jpg
        subtitle: Group Project 2
        title: Homework 2
        url: blogs/homework2
      - image: pic04.jpgm
        subtitle: Resume
        title: My CV
        url: blogs/cv.pdf
      - image: pic05.jpg
        subtitle: 
        title: To be added
        url: blogs/
      - image: pic06.jpg
        subtitle: 
        title: To be added
        url: blogs/ipsum
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "XXX"
    title: Massa libero
    url: blogs
